### ISSUE TITLE
Can't build docker image

### ISSUE THREAD

**Issue by guss77** [pawelkorus/kio-aws#2]
When building the image, we immediately get an error:

```
$ docker build -t kio-aws .
Sending build context to Docker daemon  345.6kB
Step 1/14 : FROM pawelkorus/cpp-dev
pull access denied for pawelkorus/cpp-dev, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by pawelkorus** [comment]
This is because as a base image I used my another image which is here https://github.com/pawelkorus/dockerfiles/tree/master/cpp-dev. So, first you need to build cpp-dev image and then you should be able to build this one.

Please keep in mind that this kio-aws is far from being usable. Unfortunately I don't have enough time to finish it.

**Comment by guss77** [comment]
Noted, thanks. It may be a good idea to add a comment in the README about building the dep first (otherwise docker tries to find it in the hub). I understand "not enough time" better than most, so I'll write up the README comment and submit a PR for that :-).
